name: Build and release

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Get dependencies
        run: yarn

      - name: Build app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          use_vue_cli: true
          github_token: ${{ secrets.github_token }}

          # If tag on commit starts with 'v' then also release build
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
