name: Build and release

on:
  push:
    branches:
      - "master"
    tags:
      - v*

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Get dependencies
        run: npm i

      - name: Build app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.github_token }}

          # If tag on commit starts with 'v' then also release build
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
